PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bike_settings (id TEXT PRIMARY KEY, tank_l REAL NOT NULL DEFAULT 14, consumption_l100 REAL NOT NULL DEFAULT 3.2, fuel_price REAL NOT NULL DEFAULT 2.525, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS trips (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT, departure TEXT NOT NULL, destination TEXT NOT NULL, distance_km REAL NOT NULL, fuel_l REAL NOT NULL, fuel_cost REAL NOT NULL, round_trip INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS favorites (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT, departure TEXT NOT NULL, destination TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips(created_at);
